version: '3.8'
services:
  ollama-server:
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
    volumes:
      - F:\Docker\ollama\ollama:/root/.ollama  # Changed volume path
    restart: unless-stopped
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            count: 1
            capabilities: [gpu]

  ollama-webui:
    image: ghcr.io/ollama-webui/ollama-webui:main
    container_name: ollama-webui
    restart: unless-stopped
    volumes:
      - F:\Docker\ollama\webui:/app/backend/data  # Changed volume path
    ports:
      - "3010:8080"
    environment:
      - OLLAMA_API_BASE_URL=http://ollama-server:11434/api  # Assuming "ollama-server" is the service name
    extra_hosts:
      - "host.docker.internal:host-gateway"
