version: '3.7'

services:
  jellyfin:
    image: jellyfin/jellyfin:latest
    container_name: jellyfin
    restart: unless-stopped
    volumes:
      - E:\video:/media/video
      - F:\Docker\jellyfin\cache:/cache
      - F:\Docker\jellyfin\config:/config
    ports:
      - "8096:8096"
      - "8920:8920"
    environment:
      - TZ=Europe/Amsterdam
    networks:
      - jellyfin_network

networks:
  jellyfin_network:
    driver: bridge
